spring.application.name=laptop
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/laptopshop
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.security.user.name=hung
spring.security.user.password=123456
# Spring MVC view prefix
#spring.mvc.view.prefix: /WEB-INF/jsp/
#spring.mvc.view.suffix: .jsp
# default = 1MB
spring.servlet.multipart.max-file-size=50MB

# default = 10MB (form data)
spring.servlet.multipart.max-request-size=50MB
# ===== DEFAULT ADMIN (seed when app start) =====
app.admin.email=mr.quanghung@gmail.com
app.admin.password=12345678
app.admin.full-name=Administrator
server.port=8088

# VNPAY MOCK (LOCAL)
vnpay.tmnCode=MOCK_TMN
vnpay.hashSecret=MOCK_SECRET_123456
vnpay.payUrl=http://localhost:8088/mock-vnpay/pay
vnpay.returnUrl=http://localhost:8088/payment/vnpay/return
vnpay.ipnUrl=http://localhost:8088/payment/vnpay/ipn


# ===== SPRING SESSION (store session in DB) =====
spring.session.store-type=jdbc
spring.session.timeout=30m




gemini.baseUrl=https://generativelanguage.googleapis.com
gemini.apiKey=AIzaSyBbtMdx1FU2VpYIm6u8yhEtXwgy3ubxDfg
gemini.model=gemini-2.5-flash

spring.session.jdbc.initialize-schema=always

