# ===============================
# APPLICATION
# ===============================
spring.application.name=laptop
server.port=8088


# ===============================
# DATABASE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/laptopshop?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# ===============================
# DEFAULT ADMIN (SEED)
# ===============================
app.admin.email=mr.quanghung@gmail.com
app.admin.password=123456
app.admin.full-name=Administrator


# ===============================
# SPRING SESSION (JDBC)
# ===============================
spring.session.store-type=jdbc
spring.session.timeout=30m
spring.session.jdbc.initialize-schema=always

# ✅ giảm lỗi race/duplicate và dễ debug session
spring.session.jdbc.table-name=SPRING_SESSION
logging.level.org.springframework.session=INFO


# ===============================
# VNPAY SANDBOX
# ===============================
# VNPAY Sandbox (từ email bạn nhận)
vnpay.tmnCode=5BIX0U8K
vnpay.hashSecret=P52I9SSQDW79ZOXGVZR3O8Q83A5NA1ZR
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

# MVC backend nhận return
vnpay.returnUrl=http://localhost:8088/payment/vnpay/return


# Tạm thời KHÔNG dùng IPN khi demo local
# vnpay.ipnUrl=

# ===============================
# GEMINI AI
# ===============================
gemini.baseUrl=https://generativelanguage.googleapis.com
gemini.model=gemini-2.5-flash

gemini.apiKey=AIzaSyBJunpJ2_8UuWSocmCuw1w1Bd2aqUJhhvM

